/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend;

import entities.Usuario;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import org.springframework.http.ResponseEntity;
import org.springframework.web.client.RestTemplate;

/**
 *
 * @author jonathan
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        loadUsuarios();
        ImageIcon myimage = new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("spotify_logo.png")));
        Image img1 = myimage.getImage();
        Image img2 = img1.getScaledInstance(logo_uffsfy.getWidth(), logo_uffsfy.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon i = new ImageIcon(img2);
        logo_uffsfy.setIcon(i);
        
    }
    
    public void loadUsuarios() {
        RestTemplate req = new RestTemplate();
        
        ResponseEntity<Usuario[]> response = req.getForEntity("http://localhost:8080/usuarios", Usuario[].class);
        
        Usuario[] usuarios = response.getBody();
        
        for (var c : usuarios) {
            cbUsuario.addItem(c.id + " - " + c.nome);
        }
    }
    
    public void acessaUsuario() {
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        btnUsuarioCad = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        cbUsuario = new javax.swing.JComboBox<>();
        jPanel7 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtSenha = new javax.swing.JPasswordField();
        jPanel8 = new javax.swing.JPanel();
        btnLogin = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        logo_uffsfy = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("UFFSFY");

        jPanel3.setPreferredSize(new java.awt.Dimension(435, 430));

        jPanel4.setPreferredSize(new java.awt.Dimension(430, 102));

        jLabel1.setFont(new java.awt.Font("Pagul", 1, 18)); // NOI18N
        jLabel1.setText("Bem vindo");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addComponent(jLabel1)
                .addContainerGap(172, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(40, 40, 40))
        );

        jPanel3.add(jPanel4);

        jPanel5.setPreferredSize(new java.awt.Dimension(430, 50));

        btnUsuarioCad.setText("Cadastre-se");
        btnUsuarioCad.setPreferredSize(new java.awt.Dimension(250, 30));
        btnUsuarioCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuarioCadActionPerformed(evt);
            }
        });
        jPanel5.add(btnUsuarioCad);

        jPanel3.add(jPanel5);

        jPanel1.setPreferredSize(new java.awt.Dimension(430, 135));

        jPanel9.setPreferredSize(new java.awt.Dimension(250, 50));
        jPanel9.setLayout(new java.awt.BorderLayout(4, 4));

        jLabel5.setText("Usuario");
        jPanel9.add(jLabel5, java.awt.BorderLayout.PAGE_START);

        cbUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbUsuarioActionPerformed(evt);
            }
        });
        jPanel9.add(cbUsuario, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel9);

        jPanel7.setPreferredSize(new java.awt.Dimension(250, 50));
        jPanel7.setLayout(new java.awt.BorderLayout(4, 4));

        jLabel3.setText("Senha");
        jPanel7.add(jLabel3, java.awt.BorderLayout.PAGE_START);

        txtSenha.setToolTipText("*****");
        txtSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSenhaActionPerformed(evt);
            }
        });
        jPanel7.add(txtSenha, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel7);

        jPanel3.add(jPanel1);

        jPanel8.setPreferredSize(new java.awt.Dimension(430, 100));

        btnLogin.setText("Login");
        btnLogin.setPreferredSize(new java.awt.Dimension(250, 30));
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jPanel8.add(btnLogin);

        jPanel3.add(jPanel8);

        getContentPane().add(jPanel3, java.awt.BorderLayout.WEST);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setPreferredSize(new java.awt.Dimension(435, 430));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(logo_uffsfy, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(254, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(logo_uffsfy, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnUsuarioCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuarioCadActionPerformed
        FrmUsuarioCad frm = new FrmUsuarioCad();
        frm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnUsuarioCadActionPerformed

    private void txtSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSenhaActionPerformed
        
    }//GEN-LAST:event_txtSenhaActionPerformed

    public Usuario obterUsuarioPorId(String id) {
        RestTemplate req = new RestTemplate();
        ResponseEntity<Usuario> response = req.getForEntity("http://localhost:8080/usuario/" + id, Usuario.class);
        Usuario usuario = response.getBody();
        if (usuario != null) {
            return usuario;
        } else {
            return null;
        }
    }
    
    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        String UsuarioSelecionado = (String) cbUsuario.getSelectedItem();
        
        if (UsuarioSelecionado != null) {
            String[] partes = UsuarioSelecionado.split(" - ");
            if (partes.length == 2) {
                String idUsuario = partes[0];
                Usuario usuario = obterUsuarioPorId(idUsuario);
                int senhaUsuario = usuario.getSenha();
                String pwd = new String(txtSenha.getPassword());
                
                // verificando se a senha esta correta
                if (pwd.equals(String.valueOf(senhaUsuario))) {
                    FrmPlaylistLista frm = new FrmPlaylistLista();
                    frm.setVisible(true);
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(this, "Senha errada, por favor digite a senha correta.");
                }
                
            } else {
                JOptionPane.showMessageDialog(this, "Formato de usuário inválido.");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Nenhum usuário selecionado.");
        }
        
    }//GEN-LAST:event_btnLoginActionPerformed

    private void cbUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            
            javax.swing.UIManager.setLookAndFeel(
                    javax.swing.UIManager.getSystemLookAndFeelClassName()
            );
            
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnUsuarioCad;
    private javax.swing.JComboBox<String> cbUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel logo_uffsfy;
    private javax.swing.JPasswordField txtSenha;
    // End of variables declaration//GEN-END:variables
}
